package:
    type:           yii2-extension
    name:           yii2-pluginmanager
    title:          ABANDONED in favour of hiqdev/composer-config-plugin
    headline:       ABANDONED
    keywords:       plugin, manager, extension, yii2
    namespace:      hiqdev\pluginmanager
    description:    |
        ABANDONED in favour of [hiqdev/composer-config-plugin](https://github.com/hiqdev/composer-config-plugin)
        =================
